language: ruby
rvm:
  - 1.9.2
  - 1.9.3
env:
  - CHEF_VERSION=10.12.0
  - CHEF_VERSION=10.14.4
  - CHEF_VERSION=10.16.4
  - CHEF_VERSION=10.18.0.rc.1
matrix:
  allow_failures:
    - env: CHEF_VERSION=10.18.0.rc.1
notifications:
  webhooks: https://www.buildheroes.com/api/projects/ecafb9f9b6badadc0d629c2cffaa4cd732ee47af/builds
